source: site_raw
destination: _site_generated

links: ["discover", "connect", "inform", "visualize", "about"]

name: West Coast Ocean Data Portal
markdown: redcarpet
highlighter: pygments

prose:
    siteurl: "http://portal.westcoastoceans.org/"
